title: Vince Times News & Blog
description: A collection of my stories, News, and creative projects.
baseurl: "" # leave this blank on Netlify
url: "" # leave blank, Netlify auto-detects

theme: minima

# Build settings
markdown: kramdown
